### ISSUE TITLE
FIFO Deadlock Case

### ISSUE THREAD

**Issue by dy877-nyu** [nyu-adb-fall17-dyaj/RepCRec#13]
begin(T0)
begin(T1)
fail(1)
fail(2)
fail(3)
fail(4)
fail(5)
fail(6)
fail(7)
fail(8)
fail(9)
fail(10)
recover(1)
recover(2)
recover(3)
recover(4)
recover(5)
recover(6)
recover(7)
recover(8)
recover(9)
recover(10)
R(T0,x2)
W(T1,x2,5)

Should T1 be able to get write lock on x2?

**Comment by ardijusufi** [comment]
Yes, I think T1 should be able to get a write lock on x2, since R(T0,x2) failed and subsequently it had no lock on x2. The read wouldn't proceed until some other transaction overwrites x2. So unless T1 "violated" the FIFO lock request in this case, the execution wouldn't be able to proceed otherwise. @dy877-nyu
